x-logging: &default-logging
  driver: "local"
  options:
    max-size: "${LOG_MAX_SIZE:-150m}"
    max-file: "${LOG_MAX_FILE:-5}"

services:

  workerserver-general:
    image: iplweb/bpp_workerserver:${DOCKER_VERSION:-latest}
    logging: *default-logging
    env_file: ${BPP_CONFIGS_DIR}/.env
    volumes:
      - staticfiles:/staticroot
      - media:/mediaroot
    depends_on:
      # Musi czekać na appserver, gdyż appserver aktualizuje ewentualnie baze danych.
      # Czy nawet w ogóle ją buduje...
      appserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: ${WORKER_GENERAL_MEM_LIMIT:-1g}
          cpus: "${WORKER_GENERAL_CPU_LIMIT:-2.0}"

  workerserver-denorm:
    image: iplweb/bpp_workerserver:${DOCKER_VERSION:-latest}
    logging: *default-logging
    env_file: ${BPP_CONFIGS_DIR}/.env
    environment:
      CELERY_QUEUE: "denorm"
    volumes:
      - staticfiles:/staticroot
      - media:/mediaroot
    depends_on:
      # Musi czekać na appserver, gdyż appserver aktualizuje ewentualnie baze danych.
      # Czy nawet w ogóle ją buduje...
      appserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: ${WORKER_DENORM_MEM_LIMIT:-1g}
          cpus: "${WORKER_DENORM_CPU_LIMIT:-1.0}"

  denorm-queue:
    # run only SINGLE service, this is only a mechanism to pass
    # PostgreSQL LISTEN to Celery queue
    image: iplweb/bpp_denorm_queue:${DOCKER_VERSION:-latest}
    logging: *default-logging
    env_file: ${BPP_CONFIGS_DIR}/.env
    # entrypoint: ["uv", "run", "src/manage.py", "denorm_queue"]
    # healthcheck:
    #   test: ["CMD-SHELL", "pgrep -f 'denorm_queue' > /dev/null"]
    #   start_period: 10s
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    restart: always
    depends_on:
      workerserver-denorm:
        condition: service_healthy

  workerserver-status:
    image: iplweb/bpp_workerserver:${DOCKER_VERSION:-latest}
    logging: *default-logging
    env_file: ${BPP_CONFIGS_DIR}/.env
    entrypoint: uv run celery -A django_bpp.celery_tasks status
    depends_on:
      workerserver-general:
        condition: service_healthy
      workerserver-denorm:
        condition: service_healthy
    profiles: ['manual']

  celerybeat:
    image: iplweb/bpp_beatserver:${DOCKER_VERSION:-latest}
    logging: *default-logging
    env_file: ${BPP_CONFIGS_DIR}/.env
    restart: always
    volumes:
      - staticfiles:/staticroot
      - media:/mediaroot
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      appserver:
        condition: service_started

  flower:
    image: mher/flower:2.0.1
    restart: always
    logging: *default-logging
    environment:
      - CELERY_BROKER_URL=amqp://${DJANGO_BPP_RABBITMQ_USER:-bpp}:${DJANGO_BPP_RABBITMQ_PASS:-bpp}@rabbitmq:${DJANGO_BPP_RABBITMQ_PORT:-5672}//
      - FLOWER_PORT=5555
      - FLOWER_URL_PREFIX=/flower
    depends_on:
      rabbitmq:
        condition: service_healthy
    expose:
      - 5555
