# AUTO-GENERATED by scripts/ensure-config-files.sh from
# defaults/netdata/go.d/docker.conf.tpl - DO NOT EDIT DIRECTLY.
#
# Kolektor go.d/docker — liczniki kontenerow (stany, health) i obrazow
# odpytywane przez Docker API (unix socket zamontowany RO w
# docker-compose.monitoring.yml).
#
# Plik jest RENDEROWANY i FORCE-SYNCOWANY przy kazdym make up/refresh/run
# (jak netdata.conf). Interwal stroisz w $BPP_CONFIGS_DIR/.env:
#   NETDATA_DOCKER_UPDATE_EVERY=30    (sekundy, domyslnie 30)
#
# Dlaczego 30 s, a nie stockowe 1 s (ani nasze wczesniejsze 3 s): przy KAZDYM
# zbiorze kolektor wola Info + ImageList + 4x ContainerList(all) (po jednym na
# status health). Na magazynie obrazow containerd (Docker 29+,
# io.containerd.snapshotter.v1) samo ImageList kosztuje ~0,6 s CPU w dockerd
# I drugie tyle w containerd. Przy 3 s netdata trzymala oba demony na ~35%
# rdzenia bez przerwy (zmierzone 2026-09-29; bez netdaty: 3%). Te metryki to
# liczniki, a nie szeregi o wysokiej rozdzielczosci — 30 s w zupelnosci starcza.
# Metryki CPU/RAM/IO per kontener i tak zbiera cgroups.plugin z cgroupfs,
# bez udzialu Docker API.

update_every: __DOCKER_UPDATE_EVERY__

jobs:
  - name: local
    address: 'unix:///var/run/docker.sock'
    timeout: 5
    # Rozmiar warstw kontenera (docker ps -s) jest kosztowny — nie zbieramy.
    collect_container_size: no
