# AUTO-GENERATED by scripts/ensure-config-files.sh from
# defaults/netdata/go.d/postgres.conf.tpl - DO NOT EDIT DIRECTLY.
# To customize DSN: edit the .tpl + values in $BPP_CONFIGS_DIR/.env
# and re-run 'make refresh' (or 'make update-configs').
update_every: 5
jobs:
  - name: bpp
    dsn: 'postgres://__PG_USER__:__PG_PASSWORD__@__PG_HOST__:__PG_PORT__/__PG_DB__?sslmode=disable'
    timeout: 10
