# AUTO-GENERATED by scripts/ensure-config-files.sh from
# defaults/netdata/go.d/postgres.conf.tpl - DO NOT EDIT DIRECTLY.
# To customize DSN: edit the .tpl + values in $BPP_CONFIGS_DIR/.env
# and re-run 'make refresh' (or 'make update-configs').
#
# Laczy sie jako read-only `bpp_monitor` (NIE uzytkownik aplikacji BPP) -
# rola tworzona przez `make create-monitoring-user`. Haslo: __PG_MON_PASSWORD__
# podstawiane z DJANGO_BPP_PG_MONITOR_PASSWORD.
update_every: 5
jobs:
  - name: bpp
    dsn: 'postgres://bpp_monitor:__PG_MON_PASSWORD__@__PG_HOST__:__PG_PORT__/__PG_DB__?sslmode=disable'
    timeout: 10
